### PR TITLE
scaling page update for 24tb disk storage support

### PR DESCRIPTION
**Pull request by mjk2834**
- update screenshots for new scaling console UI
- add the doc about the 24tb disk storage support for enterprise plan

### CODE REVIEW

**Comment by mjk2834** [comment]
@davidmilito Would you be able to review this PR?

**Comment by davidmilito** [comment]
Yes. I am planning to get to it this week.
________________________________
From: mjk2834 ***@***.***>
Sent: Monday, November 7, 2022 10:08 AM
To: ibm-cloud-docs/Db2onCloud ***@***.***>
Cc: David Milito ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/Db2onCloud] scaling page update for 24tb disk storage support (PR #80)

@davidmilito Would you be able to review this PR? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <ibm-cloud-docs/Db2onCloud/pull/80/c1305753197 ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@davidmilito<https://github.com/davidmilito> Would you be able to review this PR?

**Comment by davidmilito** [comment]
Please review here<https://test.cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-scale>.
________________________________
From: mjk2834 ***@***.***>
Sent: Friday, November 4, 2022 4:32 PM
To: ibm-cloud-docs/Db2onCloud ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [ibm-cloud-docs/Db2onCloud] scaling page update for 24tb disk storage support (PR #80)

update screenshots for new scaling console UI add the doc about the 24tb disk storage support for enterprise plan You can view, comment on, or merge this pull request online at: https: //github. com/ibm-cloud-docs/Db2onCloud/pull/80 ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

  *   update screenshots for new scaling console UI
  *   add the doc about the 24tb disk storage support for enterprise plan

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ibm-cloud-docs/Db2onCloud/pull/80<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80>

Commit Summary

  *   586e22d<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/commits/586e22d3f82a48420b9c53697fb342ea2c9c44f8> scaling page update for 24tb disk storage support
  *   df2b1a9<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/commits/df2b1a9926dd373f996a5f5b57f8555552189a20> new images for 24tb disk storage support

File Changes

(11 files<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files>)

  *   M flex_scaling.md<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-cbd91f6baf396da5c6802f98ea2719929b3f2c33b4f2dc7434871c5aacaa434c> (82)
  *   A images/confirm_changes_v2.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-9a27a65e9a40a73a15c9067aabbd235e72218932f68d2a8a16f2dd92eb062ae2> (0)
  *   A images/pause_rebalance.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-becea3c04d67505bb9bf4a15ac093d54c08b29f53ce9c3b2d46dbe3469f32dd1> (0)
  *   A images/rebalance_status_v1.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-9f0ca509c96e0041ea2a1e2eec0ebb84c23d2501e75039690a6bc8e8c3f1fda5> (0)
  *   A images/reclaim.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-a7b056c942ddf7c9b91f1ef9df7fbcd95042ddead7fb9a542e26a0b8a9230659> (0)
  *   A images/reclaimed.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-c999da33fa901567a45907ee1fc3e5ad2bb5b76265f7df12e057b1a84e770bdd> (0)
  *   A images/resume_reb.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-abc37a37eb6184eca6669fa2b46a478f1af2c8e910374fec65ff9c5b6e76f1c4> (0)
  *   A images/scaling_confirmation.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-698e21ac8e7e7f400af9fe02e102b473c1ba75526a8a8c1b6c6672ade600216c> (0)
  *   A images/scaling_v1.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-9015c58bfc67430a43eaa859ef87de2e9ec389d033c1d94163abec7e1e97a4d7> (0)
  *   A images/start_rebalance.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-fe740e6655c412db411566e3304f7887fb63be24730c40809c3041001645dc4d> (0)
  *   A images/user_created_tb_prompt.png<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80/files#diff-7a56a51e1d146ca19a43363f8149167b9e27e3814264701d22dad74c02d87d4a> (0)

Patch Links:

  *   https://github.com/ibm-cloud-docs/Db2onCloud/pull/80.patch<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80.patch>
  *   https://github.com/ibm-cloud-docs/Db2onCloud/pull/80.diff<https://github.com/ibm-cloud-docs/Db2onCloud/pull/80.diff>

**Comment by mjk2834** [comment]
@davidmilito I've made some changes in the external doc based on our team's review. Would you reflect the changes on our testing site?

**Comment by mjk2834** [comment]
@davidmilito I made few changes in the doc based on the feedback I got from our team. Could you please update our recent scaling doc on our testing site?

**Pull request closed without merging**
